export const countriesWithStages = [
  {
    country: "Poland",
    stages: [
      { name: "Swietajno", distance: 18.5 },
      { name: "Jelonek", distance: 18.1 },
      { name: "Gajrowskie", distance: 10.0 },
      { name: "Pietrasze", distance: 9.7 },
      { name: "Dybowo", distance: 8.5 },
      { name: "Chelchy", distance: 8.5 },
      { name: "Mikolajki", distance: 9.4 },
      { name: "Zawada", distance: 9.5 },
      { name: "Gmina Mragowo", distance: 4.4 },
      { name: "Czerwonki", distance: 4.5 },
      { name: "Kosewo", distance: 4.8 },
      { name: "Probark", distance: 4.6 },
    ],
  },
  {
    country: "Latvia",
    stages: [
      { name: "Vecpils", distance: 16.3 },
      { name: "Kagene", distance: 16.3 },
      { name: "Mazilmaja", distance: 8.5 },
      { name: "Kirsits", distance: 8.4 },
      { name: "Baznica", distance: 7.6 },
      { name: "Strokacs", distance: 7.7 },
      { name: "Podnieki", distance: 9.9 },
      { name: "Dinsdurbe", distance: 9.9 },
      { name: "Kalvene", distance: 4.9 },
      { name: "Cerpi", distance: 4.9 },
      { name: "Krote", distance: 4.9 },
      { name: "Kaleti", distance: 5.0 },
    ],
  },
  {
    country: "Mexico",
    stages: [
      { name: "El Chocolate", distance: 26.68 },
      { name: "Otates", distance: 24.74 },
      { name: "Ortega", distance: 13.1 },
      { name: "Las Minas", distance: 11.46 },
      { name: "Ibarrilla", distance: 12.92 },
      { name: "Derramadero", distance: 7.18 },
      { name: "El Brinco", distance: 10.51 },
      { name: "Guanajuatito", distance: 10.62 },
      { name: "Alfaro", distance: 8.0 },
      { name: "Mesa Cuata", distance: 8.8 },
      { name: "San Diego", distance: 5.78 },
      { name: "El Mosquito", distance: 6.84 },
    ],
  },
  {
    country: "Croatia",
    stages: [
      { name: "Bliznec", distance: 25.56 },
      { name: "Trakošćan", distance: 25.56 },
      { name: "Vrbno", distance: 12.7 },
      { name: "Zagorska Sela", distance: 12.7 },
      { name: "Kumrovec", distance: 12.94 },
      { name: "Grdanjci", distance: 12.86 },
      { name: "Stojdraga", distance: 10.24 },
      { name: "Mali Lipovec", distance: 10.24 },
      { name: "Hartje", distance: 7.79 },
      { name: "Kostanjevac", distance: 8.7 },
      { name: "Krašić", distance: 8.77 },
      { name: "Petruš Vrh", distance: 8.77 },
    ],
  },
  {
    country: "Sardegna",
    stages: [
      { name: "Rena Majore", distance: 31.53 },
      { name: "Monte Olia", distance: 31.62 },
      { name: "Littichedda", distance: 13.3 },
      { name: "Ala del Sardi", distance: 18.22 },
      { name: "Mamone", distance: 16.45 },
      { name: "Li Pinnenti", distance: 7.6 },
      { name: "Malti", distance: 7.73 },
      { name: "Bassacutena", distance: 7.49 },
      { name: "Bortigiadas", distance: 9.02 },
      { name: "Sa Mela", distance: 9.13 },
      { name: "Monte Muvri", distance: 7.51 },
      { name: "Monte Acuto", distance: 7.44 },
    ],
  },
  {
    country: "Kenya",
    stages: [
      { name: "Malewa", distance: 9.7 },
      { name: "Tarambete", distance: 9.63 },
      { name: "Moi North", distance: 5.46 },
      { name: "Marula", distance: 5.48 },
      { name: "Wileli", distance: 4.92 },
      { name: "Kingono", distance: 4.41 },
      { name: "Soysambu", distance: 20.67 },
      { name: "Mbaruk", distance: 20.23 },
      { name: "Sugunoi", distance: 9.74 },
      { name: "Nakuru", distance: 9.98 },
      { name: "Kanyawa", distance: 10.7 },
      { name: "Kanyawa - Nakura", distance: 10.69 },
    ],
  },
  {
    country: "Estonia",
    stages: [
      { name: "Otepää", distance: 17.07 },
      { name: "Rebaste", distance: 17.07 },
      { name: "Nüpli", distance: 8.6 },
      { name: "Truuta", distance: 8.6 },
      { name: "Koigu", distance: 8.47 },
      { name: "Kooraste", distance: 8.47 },
      { name: "Elva", distance: 11.82 },
      { name: "Metsalaane", distance: 11.56 },
      { name: "Vahessaare", distance: 6.17 },
      { name: "Külaaseme", distance: 6.17 },
      { name: "Vissi", distance: 5.63 },
      { name: "Vellavere", distance: 5.63 },
    ],
  },
  {
    country: "Finland",
    stages: [
      { name: "Leustu", distance: 11.09 },
      { name: "Lahdenkyla", distance: 11.0 },
      { name: "Saakoski", distance: 4.83 },
      { name: "Maahi", distance: 4.73 },
      { name: "Painaa", distance: 6.41 },
      { name: "Peltola", distance: 6.14 },
      { name: "Paijala", distance: 22.92 },
      { name: "Ruokolahti", distance: 22.9 },
      { name: "Honkanen", distance: 10.41 },
      { name: "Venkajarvi", distance: 10.35 },
      { name: "Vehmas", distance: 12.57 },
      { name: "Hatanpaa", distance: 12.5 },
    ],
  },
  {
    country: "Portugal",
    stages: [
      { name: "Baião", distance: 30.32 },
      { name: "Caminha", distance: 31.21 },
      { name: "Fridão", distance: 16.72 },
      { name: "Marão", distance: 15.12 },
      { name: "Ponte de Lima", distance: 14.77 },
      { name: "Viana do Castelo", distance: 7.87 },
      { name: "Ervideiro", distance: 7.3 },
      { name: "Celeiro", distance: 8.18 },
      { name: "Touca", distance: 7.51 },
      { name: "Vila Boa", distance: 7.39 },
      { name: "Carrazedo", distance: 7.48 },
      { name: "Anjos", distance: 7.39 },
      { name: "Fafe", distance: 11.3 },
      { name: "Villa Pouca", distance: 11.0 },
      { name: "Barbosa", distance: 5.7 },
      { name: "Passos", distance: 5.5 },
      { name: "Moreira do Rei", distance: 5.5 },
      { name: "Ruivães", distance: 5.5 },
    ],
  },
  {
    country: "Sweden",
    stages: [
      { name: "Hof-Finnskog", distance: 21.47 },
      { name: "Åsnes", distance: 21.46 },
      { name: "Spikbrenna", distance: 11.07 },
      { name: "Lauksjøen", distance: 10.95 },
      { name: "Åslia", distance: 10.39 },
      { name: "Knapptjernet", distance: 10.51 },
      { name: "Vargasen", distance: 8.24 },
      { name: "Lövstaholm", distance: 8.24 },
      { name: "Älgsjön", distance: 3.37 },
      { name: "Ekshärad", distance: 3.37 },
      { name: "Stora Jangen", distance: 4.86 },
      { name: "Sunne", distance: 4.86 },
      { name: "Umeå", distance: 10.8 },
      { name: "Sandbacka", distance: 10.8 },
      { name: "Ersmark", distance: 10.1 },
      { name: "Ersboda", distance: 10.0 },
      { name: "Umeå Sprint", distance: 5.2 },
      { name: "Haga", distance: 5.0 },
    ],
  },
  {
    country: "Chile",
    stages: [
      { name: "Bio Bío", distance: 34.72 },
      { name: "Arauco", distance: 34.79 },
      { name: "Coronel", distance: 17.97 },
      { name: "Lota", distance: 16.73 },
      { name: "Santa Juana", distance: 16.87 },
      { name: "Los Angeles", distance: 10.79 },
      { name: "San Rosendo", distance: 10.08 },
      { name: "Laja", distance: 7.87 },
      { name: "Yumbel", distance: 7.75 },
      { name: "Florida", distance: 8.21 },
      { name: "Hualqui", distance: 8.09 },
      { name: "Reputo", distance: 8.53 },
    ],
  },
  {
    country: "Central European",
    stages: [
      { name: "Rouské", distance: 32.36 },
      { name: "Lukoveček", distance: 32.34 },
      { name: "Raztoka", distance: 15.4 },
      { name: "Žabárna", distance: 15.42 },
      { name: "Provodovice", distance: 16.99 },
      { name: "Chvalčov", distance: 16.94 },
      { name: "Vítová", distance: 8.77 },
      { name: "Brusné", distance: 8.77 },
      { name: "Libosváry", distance: 14.73 },
      { name: "Rusava", distance: 14.64 },
      { name: "Osíčko", distance: 8.94 },
      { name: "Botarell", distance: 8.65 },
    ],
  },
  {
    country: "Mediterraneo",
    stages: [
      { name: "Asco", distance: 29.2 },
      { name: "Ponte", distance: 28.63 },
      { name: "Monte Cinto", distance: 15.15 },
      { name: "Albarello", distance: 16.16 },
      { name: "Capannace", distance: 20.45 },
      { name: "Serra Di Cuzzioli", distance: 7.66 },
      { name: "Maririe", distance: 8.47 },
      { name: "Poggiola", distance: 8.47 },
      { name: "Monte Alloradu", distance: 10.74 },
      { name: "Ravin de Finelio", distance: 9.46 },
      { name: "Cabanella", distance: 10.09 },
      { name: "Moltifao", distance: 11.17 },
    ],
  },
  {
    country: "Pacifico",
    stages: [
      { name: "Talao", distance: 31.44 },
      { name: "Talanghilirair", distance: 32.4 },
      { name: "SungaiKunit", distance: 14.58 },
      { name: "Sangir Balai Janggo", distance: 15.53 },
      { name: "South Solok", distance: 16.87 },
      { name: "Kebun Raya Solok", distance: 8.7 },
      { name: "Batukangkung", distance: 8.76 },
      { name: "Abai", distance: 5.37 },
      { name: "Moearaikoer", distance: 6.34 },
      { name: "Bidaralam", distance: 7.73 },
      { name: "Loeboekmalaka", distance: 7.73 },
      { name: "Gunung Tujuh", distance: 9.14 },
    ],
  },
  {
    country: "Oceania",
    stages: [
      { name: "Ruakaka", distance: 10.98 },
      { name: "Doctors Hill", distance: 10.98 },
      { name: "Ahuroa", distance: 6.6 },
      { name: "Ahuroa - Waipu", distance: 6.6 },
      { name: "Ruakaka - Maungaturoto", distance: 4.37 },
      { name: "Maungaturoto", distance: 4.37 },
      { name: "Waiwera", distance: 18.03 },
      { name: "Tahekeroa", distance: 18.02 },
      { name: "Noakes Hill", distance: 9.51 },
      { name: "Orewa", distance: 9.23 },
      { name: "Tahekeroa - Orewa", distance: 8.51 },
      { name: "Makarau", distance: 8.55 },
    ],
  },
  {
    country: "Scandia",
    stages: [
      { name: "Holtjønn", distance: 30.93 },
      { name: "Hengeltjønn", distance: 31.84 },
      { name: "Fyresvatn", distance: 17.1 },
      { name: "Russvatn", distance: 16.79 },
      { name: "Tovsli", distance: 13.75 },
      { name: "Kottjønn", distance: 6.62 },
      { name: "Fordol", distance: 5.43 },
      { name: "Fyresdal", distance: 5.43 },
      { name: "Ljosdalstjønn", distance: 9.37 },
      { name: "Dagtrolltjønn", distance: 9.27 },
      { name: "Tovslioytjorn", distance: 7.52 },
      { name: "Bergsøytjønn", distance: 7.29 },
    ],
  },
  {
    country: "Iberia",
    stages: [
      { name: "Santes Creus", distance: 18.98 },
      { name: "La Llacuna", distance: 18.98 },
      { name: "Seguer", distance: 9.74 },
      { name: "Esblada", distance: 9.74 },
      { name: "Montagut", distance: 9.24 },
      { name: "Aiguamúrcia", distance: 9.24 },
      { name: "Alforja", distance: 16.28 },
      { name: "Les Irles", distance: 16.28 },
      { name: "Duesaigües", distance: 8.94 },
      { name: "Les Voltes", distance: 8.94 },
      { name: "Montclar", distance: 7.33 },
      { name: "Botarell", distance: 7.33 },
    ],
  },
  {
    country: "Japan",
    stages: [
      { name: "Lake Mikawa", distance: 19.89 },
      { name: "Kudarisawa", distance: 19.88 },
      { name: "Oninotaira", distance: 11.38 },
      { name: "Okuwacho", distance: 11.37 },
      { name: "Habu Dam", distance: 10.27 },
      { name: "Habucho", distance: 10.28 },
      { name: "Nenoue Plateau", distance: 13.74 },
      { name: "Tegano", distance: 13.74 },
      { name: "Higashino", distance: 6.92 },
      { name: "Hokono Lake", distance: 6.92 },
      { name: "Nenoue Highlands", distance: 6.81 },
      { name: "Moltifao", distance: 6.81 },
    ],
  },
  {
    country: "Monte-Carlo",
    stages: [
      { name: "La Bollène-Vésubie - Peïra Cava", distance: 18.51 },
      { name: "Peïra Cava - La Bollène-Vésubie", distance: 18.18 },
      { name: "La Bollène-Vésubie - Col de Turini", distance: 9.21 },
      { name: "Pra d'Alart", distance: 8.88 },
      { name: "La Maïris", distance: 9.3 },
      { name: "Baisse de Patronel", distance: 9.3 },
      { name: "Saint-Léger-les-Mélèzes - La Bâtie-Neuve", distance: 16.79 },
      { name: "La Bâtie-Neuve - Saint-Léger-les-Mélèzes", distance: 16.64 },
      { name: "Moissière", distance: 8.18 },
      { name: "Ancelle", distance: 8.03 },
      { name: "Ravin de Coste Belle", distance: 8.6 },
      { name: "Les Borels", distance: 8.6 },
      { name: "Briançonnet-Entrevaux", distance: 14.3 },
      { name: "Entrevaux-Briançonnet", distance: 13.7 },
      { name: "Les Vénières", distance: 6.9 },
      { name: "Parbiou", distance: 6.2 },
      { name: "Le Champ", distance: 7.4 },
      { name: "Pertus", distance: 7.4 },
    ],
  },
  {
    country: "Greece",
    stages: [
      { name: "Gravia", distance: 24.64 },
      { name: "Prosilio", distance: 24.64 },
      { name: "Mariolata", distance: 13.51 },
      { name: "Karoutes", distance: 13.51 },
      { name: "Viniani", distance: 11.12 },
      { name: "Delphi", distance: 11.12 },
      { name: "Eptalofos", distance: 10.39 },
      { name: "Lilea", distance: 10.39 },
      { name: "Parnassós", distance: 5.57 },
      { name: "Bauxites", distance: 5.57 },
      { name: "Drosochori", distance: 8.68 },
      { name: "Amfissa", distance: 8.68 },
      { name: "Harvati", distance: 14.1 },
      { name: "Pisia", distance: 14.2 },
      { name: "Drosopigi - Aghia Triada", distance: 8.8 },
      { name: "Perachora", distance: 8.8 },
      { name: "Irini - Schinos", distance: 8.3 },
      { name: "Posidonia", distance: 8.2 },
    ],
  },
];

export const categoriesWithCars = [
  {
    category: "WRC",
    cars: [
      "Ford Puma Rally1 HYBRID ‘23",
      "Ford Puma Rally1 HYBRID ‘24",
      "Hyundai i20 N Rally1 HYBRID ‘23",
      "Hyundai i20 N Rally1 HYBRID ‘24",
      "Toyota GR Yaris Rally1 HYBRID ‘23",
      "Toyota GR Yaris Rally1 HYBRID ‘24",
    ],
  },
  {
    category: "WRC2",
    cars: [
      "Citroën C3 Rally2",
      "Ford Fiesta Rally2",
      "Hyundai i20 N Rally2",
      "ŠKODA Fabia RS Rally2",
      "ŠKODA Fabia Rally2 Evo",
      "Toyota GR Yaris Rally2",
      "Volkswagen Polo GTI R5",
    ],
  },
  {
    category: "Junior WRC",
    cars: ["Ford Fiesta Rally3", "Ford Fiesta Rally3 Evo"],
  },
  {
    category: "World Rally Car: 2017-2021",
    cars: [
      "Citroën C3 WRC",
      "Ford Fiesta WRC",
      "Hyundai i20 Coupe WRC ‘21",
      "Volkswagen Polo 2017",
    ],
  },
  {
    category: "World Rally Car: 2012-2016",
    cars: ["Citroen DS3 WRC ‘12", "MINI John Cooper Works WRC", "Volkswagen Polo R WRC 2013"],
  },
  {
    category: "World Rally Car: 1997-2011",
    cars: [
      "Citroën Xsara WRC",
      "Citroën C4 WRC",
      "Ford Focus WRC ‘99",
      "Ford Focus RS Rally 2001",
      "Mitsubishi Lancer Evolution VI",
      "Ford Focus RS Rally 2008",
      "MINI Countryman Rally Edition",
      "Peugeot 206 Rally",
      "Seat Córdoba WRC",
      "ŠKODA Fabia WRC",
      "SUBARU Impreza 1998",
      "SUBARU Impreza 2001",
      "SUBARU Impreza 2008",
    ],
  },
  {
    category: "Rally2",
    cars: [
      "Ford Fiesta R5 MK7 Evo 2",
      "Peugeot 208 T16 R5",
      "ŠKODA Fabia Rally2 Evo",
      "ŠKODA Fabia RS Rally2",
      "Volkswagen Polo GTI R5",
    ],
  },
  {
    category: "Rally3",
    cars: ["Ford Fiesta Rally3", "Renault Clio Rally3"],
  },
  {
    category: "Rally4",
    cars: [
      "Citroën C2 R2 Max",
      "Ford Fiesta MK8 Rally4",
      "Opel Adam R2",
      "Opel Corsa Rally4",
      "Peugeot 208 Rally4",
      "Renault Clio Rally4",
      "Renault Twingo II",
    ],
  },
  {
    category: "NR4/R4",
    cars: ["Mitsubishi Lancer Evolution X", "DJM Motorsport McRae R4", "SUBARU WRX STI NR4"],
  },
  {
    category: "S2000",
    cars: ["Fiat Grande Punto Abarth S2000", "Opel Corsa S2000", "Peugeot 207 S2000"],
  },
  {
    category: "S1600",
    cars: [
      "Citroën Saxo Super 1600",
      "Citroën C2 Super 1600",
      "Ford Puma S1600",
      "Peugeot 206 S1600",
      "Renault Clio S1600",
    ],
  },
  {
    category: "F2 Kit Car",
    cars: [
      "Citroën Xsara Kit Car",
      "Ford Escort Mk 6 Maxi",
      "Peugeot 306 Maxi",
      "Renault Maxi Mégane",
      "Seat Ibiza Kit Car",
      "Vauxhall Astra Rally Car",
      "Volkswagen Golf IV Kit Car",
    ],
  },
  {
    category: "Group A",
    cars: [
      "Ford Escort RS Cosworth",
      "Lancia Delta HF Integrale",
      "Mitsubishi Galant VR4",
      "SUBARU Legacy RS",
      "SUBARU Impreza 1995",
    ],
  },
  {
    category: "Group B (4WD)",
    cars: [
      "Audi Sport quattro S1 (E2)",
      "Ford RS200",
      "Lancia Delta S4",
      "MG Metro 6R4",
      "Peugeot 205 T16 Evo 2",
    ],
  },
  {
    category: "Group B (RWD)",
    cars: ["BMW M1 Procar Rally", "Lancia 037 Evo 2", "Opel Manta 400", "Porsche 911 SC RS"],
  },
  {
    category: "H3 (RWD)",
    cars: [
      "BMW M3 Evo Rally",
      "Ford Sierra Cosworth RS500",
      "Ford Escort MK2 McRae Motorsport",
      "Renault 5 Turbo",
      "Lancia Stratos",
      "Opel Ascona 400",
    ],
  },
  {
    category: "H2 (RWD)",
    cars: [
      "Alpine Renault A110 1600 S",
      "Fiat 131 Abarth Rally",
      "Ford Escort RS 1600 MK1",
      "Ford Escort MK2",
      "Hillman Avenger",
      "Opel Kadett C GT/E",
      "Talbot Sunbeam Lotus",
    ],
  },
  {
    category: "H2 (FWD)",
    cars: ["Peugeot 309 GTI", "Peugeot 205 GTI", "Volkswagen Golf GTI"],
  },
  {
    category: "H1 (FWD)",
    cars: ["Lancia Fulvia HF", "MINI Cooper S", "Vauxhall Nova Sport"],
  },
];
